---
title: "Class 05: Data Visualization with GGPLOT"
format: pdf
author: "Tahmid Ahmed"
---

```{r}
#install.packages("ggplot2")
library(ggplot2)
ggplot(cars) + aes(x=speed, y=dist)
```
```{r}
ggplot(mpg) + aes(x=displ, y=hwy) +geom_point()
```

```{r}
ggplot(mpg) + aes(x=displ, y=hwy) +geom_point() + geom_smooth(method= lm, se= FALSE)
```


```{r}
ggplot(cars) + aes(x=speed, y=dist) + geom_point() + geom_smooth(method=lm, se= FALSE)
```
``` {r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
```


```{r}
ggplot(genes) + aes(x=Condition1, y=Condition2) + geom_point()
```
```{r}
ggplot(genes) + aes(x=Condition1, y=Condition2, col=State) + geom_point() 
```

```{r}
 ggplot(genes) + aes(x=Condition1, y=Condition2, col=State) + geom_point() + scale_colour_manual( values=c("blue","gray","red") )
```
```{r}
ggplot(genes) + aes(x=Condition1, y=Condition2, col=State) + geom_point() + scale_colour_manual(values=c("blue","gray","red")) +
    labs(title="Gene Expresion Changes Upon Drug Treatment",
         x="Control (no drug) ",
         y="Drug Treatment")
```

